name: CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.1', '7.4']

        name: frictionlessdata/tableschema-php PHP ${{ matrix.php-versions }} test

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP version ${{ matrix.php-versions }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Confirm PHP Version
              run: php -v

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-
            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress