name: CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest

        name: frictionlessdata/tableschema-php test

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json & composer.lock
              uses: php-actions/composer@v6
              with:
                  command: validate --strict
